<a href="https://colab.research.google.com/github/nanpolend/machine-learning/blob/master/%E5%9C%96%E5%83%8F%E5%88%86%E5%89%B2_GrabCut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>光頭傑夫製作</h1><img src="https://rolqiw.bl.files.1drv.com/y4mYqkObWmQmdJFd8pab8t8m7d_mFhh3_YG63fiAnPaG6gjahHFt0n087pF97x1W2wemm7hd4ZdiPD2OxoPtqcCD_4-Jy-fojnt97kGGWR4Hnq0-9Ny61afd7WVHVTmF_9pcr45OFDFSwLKByeQU1q9TjwKk-HsNmWVsW1eGQ4Gi-9G4pQ5DYoTxswYJ5r5dLF-kKsA1InEyrqmV3kF5pm4WQ?width=658&height=584&cropmode=none" width=160px align="left" />
<!--1789344913-276-->

## <font color=red>你有聽過去背嗎??

## <font color=red>圖像分割-GrabCut Technique
--------
![image.png](attachment:image.png)

## <font color=red>要講之前，你就要先知道mask遮罩
------
    mask是用一副二值化圖片(0和1)對另外一幅圖片進行局部的遮擋。
------
    Image mask，用選定的圖形，對處理的圖像（全部或局部）進行遮擋，來控制圖像處理的區域或處理過程。
    用於覆蓋的特點圖像或物體稱為mask或模板。
    光學圖像處理中，mask可以是膠片，濾光片等。
    mask是由0和1組成的一個二進製圖像。
    當在某一功能中應用mask時，1值區域被處理，被屏蔽的0值區域不被包括在計算中。

## <font color=red>mask遮罩怎麼運算呢?
------
![image.png](attachment:image.png)

## <font color=red>把前景、背景分出來-grabCut語法
--------
```
outputmask, bgModel, fgModel = cv2.grabCut(image,
                                           mask,
                                           rect,
                                           bgModel,
                                           fgModel,
                                           iterCount,
                                           mode)
```
--------
### output的部分有三塊，最重要的是outputmask:
    1. outputmask-會返回一塊跟輸入image一樣大小的灰階圖片  
                  裡面每個pixel的值，有四種可能:
                  Pixel value 0 => cv2.GC_BGD =>屬於背景
                  Pixel value 1 => cv2.GC_FGD =>屬於前景
                  Pixel value 2 => cv2.GC_PR_BGD=>可能屬於背景
                  Pixel value 3 => cv2.GC_PR_FGD=>可能屬於前景
--------
### input的部分
    1.image-目標照片
    2.bgModel,fgModel-就是兩個尺寸(1,65)的array，給算法存模型參數用的。
    ----
    下面兩個參數，就是要告訴算式，你打算怎麼分前後景
    3.mask-你可以用一張跟輸入圖像一樣大的二元圖像當設定值                                            
    4.rect-你也可以用框選的方式當設定值
    ----
    5.iterCount-計算過程你想要跑多少次
    6.mode-你可以用這個參數，決定你要用前面的mask當初始值，還是用rect當初始值，比如你用rect當初始值，model就知道主題在rect裡面，所以            外面的部分先自動變成背景了。  
           cv2.GC_INIT_WITH_RECT  
           cv2.GC_INIT_WITH_MASK
--------
          
   grabcut會把算出來的結果存回去 mask、bgdModel、fgdModel，沒錯就是這樣!!
    

## <font color=red>範例講解-GrabCut Technique

In [ ]:
import cv2
import numpy as np
img = cv2.imread("person.jpg")
imgCopy = img.copy()

In [ ]:
img.shape

(510, 768, 3)

In [ ]:
bgdModel = np.zeros((1,65),np.float64)
fgdModel = np.zeros((1,65),np.float64)

NameError: ignored

In [ ]:
rect = cv2.selectROI(img)
cv2.destroyAllWindows()

In [ ]:
# Draw rectangle
x,y,w,h = rect
x,y,w,h

(183, 101, 451, 324)

In [ ]:
#我們這邊是採用rect的選取方式，所以mask要設None，要不然error
cv2.grabCut(img,None,rect,bgdModel,fgdModel,5,cv2.GC_INIT_WITH_RECT)
# grabcut會把算出來的結果存回去 mask、bgdModel、fgdModel

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 array([[3.16931929e-01, 2.15906045e-01, 1.48120164e-01, 1.97486898e-01,
         1.21554964e-01, 4.54001799e+01, 1.00736854e+02, 8.24678872e+01,
         3.62922758e+01, 6.29786326e+01, 7.79666020e+01, 5.42293211e+01,
         9.85297503e+01, 1.03785482e+02, 3.56281709e+01, 8.48539624e+01,
         6.60936719e+01, 2.89590683e+01, 5.21228185e+01, 4.46442344e+01,
         2.61636921e+01, 2.25387726e+01, 2.34621874e+01, 2.25387726e+01,
         2.87398765e+01, 2.58527705e+01, 2.34621874e+01, 2.58527705e+01,
         3.02119934e+01, 4.81230452e+01, 5.82091822e+01, 7.11424160e+01,
         5.82091822e+01, 9.76236735e+01, 1.19387794e+02, 7.11424160e+01,
         1.19387794e+02, 1.68781196e+02, 2.35085355e+02, 2.39670332e+02,
         2.25211622e+02, 2.39670332e+02, 3.2

In [ ]:
mask[200,:]

#讓我們看看第200row的pixel資料
#0:背景、1:前景，2:可能屬於背景，3:可能屬於前景

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [ ]:
# 把判定成背景(代碼0的)或是可能是背景的(代碼1的)都歸0
mask2 = np.where((mask==0)|(mask==2),0,1).astype('uint8')
mask2[200,:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
#我們的mask裡面有那些值
#背景、可能屬於背景、可能屬於前景
np.unique(mask)

array([0, 2, 3], dtype=uint8)

In [ ]:
#經過我們整理以後，我們的mask2裡面有那些值
#背景、前景
np.unique(mask2)

array([0, 1], dtype=uint8)

In [ ]:
#把pixel值放大一點，要不然都接近0，我想應該是看不到吧
cv2.imshow("Mask",mask*60)
cv2.imshow("Mask2",mask2*255)
cv2.imwrite("mask.jpg",mask*80)
cv2.imwrite("mask2.jpg",mask2*255)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>接著，我們要把分析的結果，套回我們的圖片

In [ ]:
img = img*mask2

#透過相乘，乘0的歸0，乘1的留下來
#但是乘不起來...

ValueError: operands could not be broadcast together with shapes (510,768,3) (510,768) 

In [ ]:
#看一下尺寸
mask2.shape

(510, 768)

In [ ]:
mask2[:,:,np.newaxis].shape

(510, 768, 1)

In [ ]:
#調整一下再來
img = img*mask2[:,:,np.newaxis]

In [ ]:
cv2.imwrite("grabcut-result.png",img)
cv2.imshow("Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>結果還是有點不完美，可以試試看調整iterCount，看看結果


## <font color=red ><答案>

In [ ]:
import cv2
import numpy as np

img = cv2.imread("person.jpg")
imgCopy = img.copy()
mask = np.zeros(img.shape[:2], np.uint8)
bgdModel = np.zeros((1,65),np.float64)
fgdModel = np.zeros((1,65),np.float64)

rect = cv2.selectROI(img)
cv2.destroyAllWindows()

for i in range(3,10):
    mask = np.zeros(img.shape[:2], np.uint8)
    bgdModel = np.zeros((1,65),np.float64)
    fgdModel = np.zeros((1,65),np.float64)
    cv2.grabCut(img,mask,rect,bgdModel,fgdModel,i,cv2.GC_INIT_WITH_RECT)
    mask2 = np.where((mask==0)|(mask==2),0,1).astype('uint8')
#     print(np.unique(mask2))
    img_copy = img.copy()
    img_copy = img_copy*mask2[:,:,np.newaxis]
    cv2.imshow(f"Image{i}",img_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>手動調整還是最符合自己的想像啦!!-做一支自己的修圖筆刷

In [ ]:
import cv2
import numpy as np
img = cv2.imread("person.jpg")
imgCopy = img.copy()

mask = np.zeros(img.shape[:2], np.uint8)
bgdModel = np.zeros((1,65),np.float64)
fgdModel = np.zeros((1,65),np.float64)

rect = cv2.selectROI(img)

x,y,w,h = rect

cv2.grabCut(img,mask,rect,bgdModel,fgdModel,5,cv2.GC_INIT_WITH_RECT)

mask2 = np.where((mask==2)|(mask==0),0,1).astype('uint8')

cv2.imshow("Mask2",mask2*255)
# cv2.imwrite("mask.png",mask*80)
# cv2.imwrite("mask2.png",mask2*255)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:
imgResult = img*mask2[:,:,np.newaxis]
cv2.imshow("Image",imgResult)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#把圖各準備一份
img_mask = img.copy()
mask2 = mask2*255
mask_copy = mask2.copy()

### 開一個Sketcher class，來處理我們的"筆刷事件"
----
```
Event:
 CV_EVENT_MOUSEMOVE     0         //滑動
 CV_EVENT_LBUTTONDOWN   1         //左鍵點擊
 CV_EVENT_RBUTTONDOWN   2         //右鍵點擊
 CV_EVENT_MBUTTONDOWN   3         //中鍵點擊
 CV_EVENT_LBUTTONUP     4         //左鍵放開
 CV_EVENT_RBUTTONUP     5         //右鍵放開
 CV_EVENT_MBUTTONUP     6         //中鍵放開
 CV_EVENT_LBUTTONDBLCLK 7         //左鍵雙擊
 CV_EVENT_RBUTTONDBLCLK 8         //右鍵雙擊
 CV_EVENT_MBUTTONDBLCLK 9         //中鍵雙擊
```
----

```
flags:
 CV_EVENT_FLAG_LBUTTON  1         //左鍵拖曳
 CV_EVENT_FLAG_RBUTTON  2         //右鍵拖曳
 CV_EVENT_FLAG_MBUTTON  4         //中鍵拖曳
 CV_EVENT_FLAG_CTRLKEY  8         //(8~15)按Ctrl不放事件
 CV_EVENT_FLAG_SHIFTKEY 16        //(16~31)按Shift不放事件
 CV_EVENT_FLAG_ALTKEY   32        //(32~39)按Alt不放事件
```

In [ ]:
class Sketcher:
    def __init__(self, windowname, dests, colors_func):

        #視窗名稱
        self.windowname = windowname

        #顯示的圖片目標
        #會塞兩張圖進來 顯示cut圖和mask圖
        self.dests = dests

        #顯示的顏色
        self.colors_func = colors_func

        #一啟動就要顯示結果
        self.show()

        #要記錄滑鼠座標位置
        self.prev_pt = None


        #把滑鼠的callback function裝上來
        #windowname是設定要把function裝在哪個視窗
        #on_mouse是下面設計的function，這個function是要給cv2.setMouseCallback呼叫的，每逢有滑鼠訊號，cv2就會把參數傳給我們的on_mouse
        cv2.setMouseCallback(self.windowname, self.on_mouse)

    def show(self):
        #就是顯示圖
        #會塞兩張圖進來 顯示cut圖和mask圖
        cv2.imshow(self.windowname  , self.dests[0])
        cv2.imshow(self.windowname + ": mask"  , self.dests[1])

    # onMouse function for Mouse Handling
    # 處理滑鼠動作的指令
    def on_mouse(self, event, x, y, flags, param):
        #point座標
        pt = (x, y)

        #當滑鼠剛按下去，就先記錄一下這個點的座標，代表畫線任務開始，只要prev_pt不是None 下面的if判斷式就會進行
        if event == cv2.EVENT_LBUTTONDOWN:
            self.prev_pt = pt
        elif event == cv2.EVENT_LBUTTONUP:  #鬆開就忘記座標，歸0，那下面線就畫不出來了，代表這個畫線任務結束
            self.prev_pt = None

        #self.prev_pt如果沒有歸零，就代表是同一個畫線任務仍在進行中
        #CV_EVENT_FLAG_LBUTTON 的意思是 有左鍵拖曳的事件發生
        #cv2.line(影像, 開始座標, 結束座標, 顏色, 線條寬度)
        if self.prev_pt and cv2.EVENT_FLAG_LBUTTON:
            #針對兩個圖分別處理標示
            for dst, color in zip(self.dests, self.colors_func()):
                #((0,0,255), 0)
                #隨著你畫線，會開始在兩張圖裡面開始標註color，第一張圖就會配你設計的(0,0,255)，如果第二張圖就會用後面那個0了
                cv2.line(dst, self.prev_pt, pt, color, 5)
            #每次畫了線就更新一下起點，那你就會畫出一條線，如果這句刪掉會怎樣?就會每次原點出發
            self.prev_pt = pt
            self.show()

In [ ]:
while True:
    #把蒐集到鍵盤的訊號存起來，下面就開始根據不同的訊號，開始不同的處理
    ch = cv2.waitKey()

    #Quit
    #按esc
    if ch == 27:
        print("exiting...")
        #存照片，不接受中文名稱
        cv2.imwrite("cut_result.png",img_mask)
        cv2.imwrite("mask_grabcut.png",mask2)
        break

    # 按r的時候Reset
    elif ch == ord('r'):
        print("重新開始...")
        img_mask = img.copy()
        mask2 = mask_copy.copy()
        #處理成0或1
        mask2 = mask2//255

        #切割、重分類
        #沒有設定rect，改用None
        cv2.grabCut(img,mask2,None,bgdModel,fgdModel,5,cv2.GC_INIT_WITH_MASK)
        mask2 = np.where((mask2==2)|(mask2==0),0,1).astype('uint8')
        #準備兩個要顯示的圖
        img_mask = img*mask2[:,:,np.newaxis]
        mask2 = mask2*255
        #'image'是sketcher show的時候，視窗的名稱
        # [img_mask, mask2] 是等一下要顯示的cut圖和mask圖
        # lambda是等一下sketch顯示的顏色
        sketch = Sketcher('image', [img_mask, mask2], lambda : ((255,0,0), 255))
        sketch.show()

    # 按了b，表示改成背景選取
    elif ch == ord('b'):
        print("處理背景...")

        sketch = Sketcher('image', [img_mask, mask2], lambda : ((0,0,255), 0))      #這裡lambda的設定就是(img_mask的顏色，mask2的顏色)，因為這是畫背景，所以mask2的顏色是0
        sketch.show()

    # 按了f，表示改成前景選取
    elif ch == ord('f'):
        print("處理前景...")
        sketch = Sketcher('image', [img_mask, mask2], lambda : ((255,0,0), 255))    #這裡lambda的設定就是(img_mask的顏色，mask2的顏色)，因為這是畫前景，所以mask2的顏色是1
        sketch.show()

    else:
#         print("進行 grabcut...")
        #處理成0或1
        mask2 = mask2//255
        #沒有設定rect，改用None
        cv2.grabCut(img,mask2,None,bgdModel,fgdModel,5,cv2.GC_INIT_WITH_MASK)
        mask2 = np.where((mask2==2)|(mask2==0),0,1).astype('uint8')
        img_mask = img*mask2[:,:,np.newaxis]
        mask2 = mask2*255
#         print("處理好了...前台看看...")
        sketch = Sketcher('image', [img_mask, mask2], lambda : ((255,0,0), 255))
        sketch.show()


cv2.destroyAllWindows()

exiting...
