<a href="https://colab.research.google.com/github/nanpolend/machine-learning/blob/master/%E8%87%89%E9%83%A8%E4%BA%94%E5%AE%98%E5%81%B5%E6%B8%AC_Detecting_facial_landmarks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>光頭傑夫製作</h1><img src="https://rolqiw.bl.files.1drv.com/y4mYqkObWmQmdJFd8pab8t8m7d_mFhh3_YG63fiAnPaG6gjahHFt0n087pF97x1W2wemm7hd4ZdiPD2OxoPtqcCD_4-Jy-fojnt97kGGWR4Hnq0-9Ny61afd7WVHVTmF_9pcr45OFDFSwLKByeQU1q9TjwKk-HsNmWVsW1eGQ4Gi-9G4pQ5DYoTxswYJ5r5dLF-kKsA1InEyrqmV3kF5pm4WQ?width=658&height=584&cropmode=none" width=160px align="left" />
<!--1789344913-343-->

## <font color=red>facial landmarks
    facial landmarks就是臉上的辨識關鍵點，透過找到這些點，你就可以進一步做更精細的臉部相關運算
-----


## <font color=red>openCV的處理方式

## <font color=red>模型1-LBF model
    
-----
    LBF就是一種演算法，中文稱為區域性二值特徵


In [ ]:
import cv2
import numpy as np

#先讀照片進來
image = cv2.imread('model.png')
#找臉
cas = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
faces = cas.detectMultiScale(image , 1.5, 5)



facemark = cv2.face.createFacemarkLBF()
facemark.loadModel("lbfmodel.yaml")
#ok確認正常運作
#關鍵是landmarks，一共68個點
ok, landmarks = facemark.fit(image , faces)
print (landmarks)

#先去掉一層tupple
for x,y in landmarks[0][0]:
        # display landmarks on "image_cropped"
        # with white colour in BGR and thickness 1
        cv2.circle(image, (int(x), int(y)), 1, (0, 0, 255), 2)

cv2.imshow('detected result', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


error: ignored

## <font color=red>模型2-face_landmark_model
    
-----


In [ ]:
import cv2
import numpy as np

#先讀照片進來
image = cv2.imread('model.png')
#找臉
cas = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
faces = cas.detectMultiScale(image , 1.5, 5)



facemark = cv2.face.createFacemarkKazemi()
facemark.loadModel("face_landmark_model.dat")
#ok確認正常運作
#關鍵是landmarks，一共68個點
ok, landmarks = facemark.fit(image , faces)
print (landmarks)


for x,y in landmarks[0][0]:
        # display landmarks on "image_cropped"
        # with white colour in BGR and thickness 1
        cv2.circle(image, (int(x), int(y)), 1, (0, 0, 255), 2)

cv2.imshow('detected result', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


(array([[[113.249344, 243.24738 ],
        [113.18795 , 277.4249  ],
        [116.084435, 310.46783 ],
        [122.025116, 343.41257 ],
        [135.02101 , 374.26416 ],
        [153.19624 , 400.90097 ],
        [176.27713 , 423.28302 ],
        [202.43298 , 441.91382 ],
        [230.76598 , 447.8179  ],
        [259.45526 , 442.13705 ],
        [285.1506  , 425.7633  ],
        [306.9965  , 404.09695 ],
        [323.70908 , 377.66833 ],
        [334.52997 , 345.33255 ],
        [338.6817  , 310.37323 ],
        [340.9434  , 275.84668 ],
        [340.29083 , 240.64882 ],
        [121.778145, 225.2586  ],
        [138.83536 , 210.43456 ],
        [161.29938 , 207.89218 ],
        [183.52773 , 211.50362 ],
        [205.39716 , 221.00558 ],
        [239.76122 , 222.07533 ],
        [263.0665  , 212.85062 ],
        [286.89572 , 208.95717 ],
        [311.1332  , 210.61974 ],
        [331.3418  , 223.75616 ],
        [224.30765 , 247.2792  ],
        [224.74762 , 271.36926 ],
        [225.

## <font color=red>landmarks的順序標註了不同的五官
----
```
    landmarks---[0, 16]----下巴
    landmarks---[17, 21]---左眉
    landmarks---[22, 26]---右眉
    landmarks---[27, 30]---鼻樑
    landmarks---[30, 35]---下鼻
    landmarks---[36, 41]---左眼
    landmarks---[42, 47]---右眼
    landmarks---[48, 59]---外唇
    landmarks---[60, 67]---內唇

```
----


## <font color=red ><小測驗>延續前面的案例，可不可以左眉毛標藍色，右眉毛標紅色

## <font color=red ><答案>

In [ ]:
import cv2
import numpy as np

#先讀照片進來
image = cv2.imread('model.png')
#找臉
cas = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
faces = cas.detectMultiScale(image , 1.5, 5)



facemark = cv2.face.createFacemarkKazemi()
facemark.loadModel("face_landmark_model.dat")
#ok確認正常運作
#關鍵是landmarks，一共68個點
ok, landmarks = facemark.fit(image , faces)
print (landmarks)

for x,y in landmarks[0][0][17:22]:
        cv2.circle(image, (int(x), int(y)), 1, (255, 0,0), 2)
for x,y in landmarks[0][0][22:27]:
        cv2.circle(image, (int(x), int(y)), 1, (0, 0, 255), 2)

cv2.imshow('detected result', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

(array([[[113.249344, 243.24738 ],
        [113.18795 , 277.4249  ],
        [116.084435, 310.46783 ],
        [122.025116, 343.41257 ],
        [135.02101 , 374.26416 ],
        [153.19624 , 400.90097 ],
        [176.27713 , 423.28302 ],
        [202.43298 , 441.91382 ],
        [230.76598 , 447.8179  ],
        [259.45526 , 442.13705 ],
        [285.1506  , 425.7633  ],
        [306.9965  , 404.09695 ],
        [323.70908 , 377.66833 ],
        [334.52997 , 345.33255 ],
        [338.6817  , 310.37323 ],
        [340.9434  , 275.84668 ],
        [340.29083 , 240.64882 ],
        [121.778145, 225.2586  ],
        [138.83536 , 210.43456 ],
        [161.29938 , 207.89218 ],
        [183.52773 , 211.50362 ],
        [205.39716 , 221.00558 ],
        [239.76122 , 222.07533 ],
        [263.0665  , 212.85062 ],
        [286.89572 , 208.95717 ],
        [311.1332  , 210.61974 ],
        [331.3418  , 223.75616 ],
        [224.30765 , 247.2792  ],
        [224.74762 , 271.36926 ],
        [225.

## <font color=red>dlib的處理方式

## <font color=red>我們需要先準備一個可以把dlib資料轉成numpy的function

In [ ]:
def shape_to_np(dlib_shape, dtype="int"):
    # 先做出一個np.array等著裝座標
    # 資料型別必須是int
    # num_parts代表有幾個特徵點
    # 因為每個座標只有x y，所以設2
    coordinates = np.zeros((dlib_shape.num_parts, 2), dtype=dtype)

    # for下去把每一個座標裝出來
    for i in range(0, dlib_shape.num_parts):
        coordinates[i] = (dlib_shape.part(i).x, dlib_shape.part(i).y)

    return coordinates

## <font color=red>開始偵測

In [ ]:
import cv2
import numpy as np
import dlib

image = cv2.imread('model.png')
gray = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)

#準備偵測器
#臉的偵測器
detector = dlib.get_frontal_face_detector()
#特徵的偵測器
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

#先找到臉，上採樣用1
rects = detector(gray, 1)

#開始對找到的臉做landmark分析
for (i, rect) in enumerate(rects):
    shape = predictor(gray, rect)
    shape = shape_to_np(shape)
    for x,y in shape:
        cv2.circle(image, (x, y), 1, (0, 0, 255), 2)
cv2.imshow('Find Face image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#轉成numpy array的結果如下
shape[27],shape[30]

(array([225, 249]), array([226, 319]))

## <font color=red ><小測驗>資料夾有一張face的照片，可不可以幫我把每個人的鼻子標註出來

## <font color=red ><答案>

In [ ]:
import cv2
import numpy as np
import dlib


# Load image:
image = cv2.imread('face.png')
image= cv2.resize(image,None,fx=1.5,fy=1.5, interpolation = cv2.INTER_AREA)
gray = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)


detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')

rects = detector(gray, 1)
#開始對找到的臉做landmark分析
for (i, rect) in enumerate(rects):
    shape = predictor(gray, rect)
    shape = shape_to_np(shape)
    for index,(x,y) in  enumerate(shape[27:31]):
        cv2.putText(image, str(index + 1), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.2, (0, 0, 255))
        cv2.circle(image, (x, y), 1, (0, 0, 255), 1)
cv2.imshow('Find Face image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>資料夾有一張mask的照片，可不可以幫我把每個人都戴上口罩

## <font color=red ><答案>

In [ ]:
import cv2
import numpy as np
import dlib


# Load image:
image = cv2.imread('face.png')
image= cv2.resize(image,None,fx=1.5,fy=1.5, interpolation = cv2.INTER_AREA)
gray = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)


detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')
rects = detector(gray, 1)
#開始對找到的臉做landmark分析
for (i, rect) in enumerate(rects):
    shape = predictor(gray, rect)
    shape = shape_to_np(shape)
    for index,(x,y) in  enumerate([shape[48],shape[54],shape[30],shape[8]]):
        cv2.putText(image, str(index + 1), (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255))
        cv2.circle(image, (x, y), 1, (0, 0, 255), 1)
cv2.imshow('Find Face image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

#先把關鍵點找出來

In [ ]:
#這樣才好計算長寬
import cv2
import numpy as np
import dlib


# Load image:
image = cv2.imread('face.png')
face_mask= cv2.imread('mask.png')
image= cv2.resize(image,None,fx=1.5,fy=1.5, interpolation = cv2.INTER_AREA)
gray = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)


detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks.dat')
rects = detector(gray, 1)
#開始對找到的臉做landmark分析
for (i, rect) in enumerate(rects):
    shape = predictor(gray, rect)
    shape = shape_to_np(shape)
    #找出臉部定位點
    # ML mouth_left
    # n  nose
    # c  chin
    x_ML,y_ML=shape[48]
    x_MR,y_MR=shape[54]
    x_n,y_n=shape[30]
    x_c,y_c=shape[8]

    #找出口罩位置  後面的數字你要自行調整
    h=int((y_c-y_n)*1.04)
    w=int((x_MR-x_ML)*1.9)
    x=x_ML-14
    y=y_n-3

    #確定目標區域
    frame_roi = image[y:y+h, x:x+w]
    #調整口罩大小
    face_mask_small = cv2.resize(face_mask, (w,h), interpolation=cv2.INTER_AREA)
    #做出口罩的遮罩
    gray_mask = cv2.cvtColor(face_mask_small, cv2.COLOR_BGR2GRAY)
    ret, mask = cv2.threshold(gray_mask, 180, 255, cv2.THRESH_BINARY_INV)
    #依照遮罩，把口罩挖出來
    masked_face = cv2.bitwise_and(face_mask_small, face_mask_small, mask=mask)
    #依照遮罩，把ROI的地方挖出洞來
    mask_inv = cv2.bitwise_not(mask)
    masked_frame = cv2.bitwise_and(frame_roi, frame_roi, mask=mask_inv)
    #合體
    image[y:y+h, x:x+w] = cv2.add(masked_face, masked_frame)


cv2.imshow('Masked image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>dlib有很多已經訓練好的模型，請參考下面連結，幫我下載shape_predictor_68_face_landmarks_GTX.dat試試看可以嗎?
-----
## [參考網址](https://github.com/davisking/dlib-models)

## <font color=red ><答案>

In [ ]:
import cv2
import numpy as np
import dlib


# Load image:
image = cv2.imread('face.png')
face_mask= cv2.imread('mask.png')
image= cv2.resize(image,None,fx=1.5,fy=1.5, interpolation = cv2.INTER_AREA)
gray = cv2.cvtColor(image , cv2.COLOR_BGR2GRAY)


detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor('shape_predictor_68_face_landmarks_GTX.dat')
rects = detector(gray, 1)
#開始對找到的臉做landmark分析
for (i, rect) in enumerate(rects):
    shape = predictor(gray, rect)
    shape = shape_to_np(shape)
    #找出臉部定位點
    x_ML,y_ML=shape[48]
    x_MR,y_MR=shape[54]
    x_n,y_n=shape[30]
    x_c,y_c=shape[8]

    #找出口罩位置  後面的數字你要自行調整
    h=int((y_c-y_n)*1.04)
    w=int((x_MR-x_ML)*1.8)
    x=x_ML-14
    y=y_n-3

    #確定目標區域
    frame_roi = image[y:y+h, x:x+w]
    #調整口罩大小
    face_mask_small = cv2.resize(face_mask, (w,h), interpolation=cv2.INTER_AREA)
    #做出口罩的遮罩
    gray_mask = cv2.cvtColor(face_mask_small, cv2.COLOR_BGR2GRAY)
    ret, mask = cv2.threshold(gray_mask, 180, 255, cv2.THRESH_BINARY_INV)
    #依照遮罩，把口罩挖出來
    masked_face = cv2.bitwise_and(face_mask_small, face_mask_small, mask=mask)
    #依照遮罩，把ROI的地方挖出洞來
    mask_inv = cv2.bitwise_not(mask)
    masked_frame = cv2.bitwise_and(frame_roi, frame_roi, mask=mask_inv)
    #合體
    image[y:y+h, x:x+w] = cv2.add(masked_face, masked_frame)


cv2.imshow('Masked image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

RuntimeError: Unable to open shape_predictor_68_face_landmarks_GTX.dat

## <font color=red>face_recognition的處理方式
----
這個方法比較簡單，不用導模型

In [ ]:
import cv2
import face_recognition


# Load image:
image = cv2.imread("face.png")

# Create images to show the results:
image_68 = image.copy()
image_5 = image.copy()


# 偵測68個特徵值:
face_landmarks_list_68 = face_recognition.face_landmarks(image)


# Draw all detected landmarks:
for face_landmarks in face_landmarks_list_68:
    for facial_feature in face_landmarks.keys():
        for p in face_landmarks[facial_feature]:
            cv2.circle(image_68, p, 2, (0, 255, 0), -1)

# 偵測5個特徵值:
face_landmarks_list_5 = face_recognition.face_landmarks(image, None, "small")

# Draw all detected landmarks:
for face_landmarks in face_landmarks_list_5:
    for facial_feature in face_landmarks.keys():
        for p in face_landmarks[facial_feature]:
            cv2.circle(image_5, p, 2, (0, 255, 0), -1)

cv2.imshow('image_68', image_68)
cv2.imshow('image_5', image_5)
cv2.waitKey(0)
cv2.destroyAllWindows()