<a href="https://colab.research.google.com/github/nanpolend/machine-learning/blob/master/%E9%82%8A%E7%B7%A3%E5%92%8C%E8%BC%AA%E5%BB%93_Edge_and_Contours.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>光頭傑夫製作</h1><img src="https://rolqiw.bl.files.1drv.com/y4mYqkObWmQmdJFd8pab8t8m7d_mFhh3_YG63fiAnPaG6gjahHFt0n087pF97x1W2wemm7hd4ZdiPD2OxoPtqcCD_4-Jy-fojnt97kGGWR4Hnq0-9Ny61afd7WVHVTmF_9pcr45OFDFSwLKByeQU1q9TjwKk-HsNmWVsW1eGQ4Gi-9G4pQ5DYoTxswYJ5r5dLF-kKsA1InEyrqmV3kF5pm4WQ?width=658&height=584&cropmode=none" width=160px align="left" />
<!--180020177X-181-->

## <font color=red>Edge and Contours - 邊緣或是輪廓
----
### 我們如果要從照片裡面，把一個物品框選出來，那當然是要先找到這個物件的邊緣或是輪廓
-----
   contour就是外廓、輪廓的意思  
   contour輪廓和edge邊緣的意思不一樣  
   在openCV的世界裏， 若Edge線條頭尾相連形成封閉的區塊，那麼它就是Contour，否則就只是Edge。  
-----
![image.png](attachment:image.png)
-----
![image-2.png](attachment:image-2.png)

## <font color=red>邊緣檢測-edge detection
-----
```
    邊緣檢測是圖像處理和計算機視覺的基本問題，
    邊緣檢測的目的是標識圖像中亮度變化明顯的點，圖像屬性中的顯著變化通常反映了屬性的重要事件和變化。
    這些包括：深度上的不連續，表面方向的不連續，物質屬性變化和場景照明變化。
    邊緣檢測是圖像處理和電腦視覺中，尤其是特徵提取中的一個研究領域。
    圖像邊緣檢測大幅度的減少了數據量，並且剔除了可以認為不相關的信息，保留了圖像重要的結構屬性。
    邊緣計算就是尋找圖像梯度在梯度方向上的極值點。
    邊緣像素是一個局部概念：它們只是指出相鄰像素之間的顯著差異。
    只要有這個極值點出現，那就是邊緣。
```

## <font color=red>方法1-cv2.Sobel
    Sobel算子是一種用於邊緣檢測的離散微分算子，它結合了高斯平滑和微分求導。該算子用於計算圖像明暗程度近似值。根據圖像
邊緣旁邊明暗程度把該區域內超過某個數的特定點記為邊緣。
    
--------
```
  dst = cv2.Sobel(src, ddepth, dx, dy[, dst[, ksize[, scale[, delta[, borderType]]]]])
```

--------
```
    dst 表示輸出的邊緣圖，其大小和通道數與輸入圖像相同
    
    src 表示需要處理的圖像
    
    ddepth 表示你要用多大的數字去記錄計算結果，-1表示採用的是與原圖像相同的深度。目標圖像的深度必須大於等於原圖像的深度
    圖像深度是指存儲每個像素值所用的位數，
    例如cv2.CV_8U，指的是8位無符號數，取值範圍為0~255，
    超出範圍則會被截斷（截斷指的是，當數值大於255保留為255，當數值小於0保留為0，其餘不變）。
    深度選擇還有：CV_16S（16位無符號數），CV_16U（16位有符號數），CV_32F（32位浮點數），CV_64F（64位浮點數）
    一般選用cv2.CV_16S
    
    dx和dy表示的是求導的階數，
    dx 表示x方向上的差分階數，取值為1或者0，
    dy 表示y方向上的差分階數，取值為1或者0，
    0表示這個方向上沒有求導，1就是這個方向上要求導

    其後是可選的參數：
    ksize是Sobel算子的大小，其值必須是正數和奇數，通常為1、3、5、7。
    
    scale是縮放導數的比例常數，默認情況下沒有伸縮係數；
    
    delta是一個可選的增量，將會加到最終的dst中，
    同樣，默認情況下沒有額外的值加到dst中；
    
    borderType是判斷圖像邊界的模式。這個參數默認值為cv2.BORDER_DEFAULT。
```
          
    
    

In [ ]:
import cv2
import numpy as np

img = cv2.imread("desk.png")

'''
分三步驟
第一步驟-
在Sobel函式的第二個引數這裡使用了cv2.CV_16S。
因為OpenCV文件中對Sobel運算元的介紹中有這麼一句：
“in the case of 8-bit input images it will result in truncated derivatives”。
即Sobel函式求完導數後會有負值，還有會大於255的值。
而原影象是uint8，即8位無符號數，所以Sobel建立的影像位數不夠，會有截斷。
因此要使用16位有符號的資料型別，即cv2.CV_16S。

第二步驟-
經過前面求導處理後，用convertScaleAbs()函式將其轉回原來的uint8形式。
否則將無法顯示影象。
convertScaleAbs()的原型為：
dst = cv2.convertScaleAbs(src[, dst[, alpha[, beta]]])
其中可選引數alpha是伸縮係數，beta是加到結果上的一個值。處理結果會返回uint8型別的圖片。

第三步驟-
由於Sobel運算元是在兩個方向計算的，最後還需要用cv2.addWeighted(...)函式將其組合起來。
其函式原型為：
dst = cv2.addWeighted(src1, alpha, src2, beta, gamma[, dst[, dtype]])
其中alpha是第一幅圖片中元素的權重，beta是第二個的權重，gamma是加到最後結果上的一個值。
'''

x = cv2.Sobel(img, cv2.CV_16S, 1, 0)
y = cv2.Sobel(img, cv2.CV_16S, 0, 1)

absX = cv2.convertScaleAbs(x)# 轉回uint8
absY = cv2.convertScaleAbs(y)

dst = cv2.addWeighted(absX, 0.8, absY, 0.2, 0)

cv2.imshow("orign", img)
cv2.imshow("absX", absX)
cv2.imshow("absY", absY)

cv2.imshow("Result", dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

DisabledFunctionError: ignored

## <font color=red>方法2-cv2.Canny
--------
```
  edges = cv2.Canny(image, threshold1, threshold2[, edges[, apertureSize[, L2gradient]]])
```

--------
```
    edges：表示輸出的邊緣圖，其大小和類型與輸入圖像相同
    
    
    image：表示輸入圖像（必須是灰階圖像）
    
    
    threshold1：表示第一個滯後性閾值
    threshold2：表示第二個滯後性閾值
    用來區分 weak edge(threshold1) 和 strong edge(threshold2)，範圍都是 0 ~ 255，
    其中較大的閾值2用於檢測影象中明顯的邊緣，但一般情況下檢測的效果不會那麼完美，邊緣檢測出來是斷斷續續的。
    所以這時候用較小的閾值1將這些間斷的邊緣連線起來。
    通常選擇 threshold1 / threshold2 = 1/2 ~ 1/3，例如 (70, 140), (70, 210)
    
    apertureSize：用來計算梯度的 kernel size，也就是 Sobel 的 ksize，其默認值為3
    
    L2gradient：選擇要用 L1 norm（絕對值平均）還是 L2 norm（平方根）當作梯度的大小。
    默認值為FALSE，預設是用 L1 norm
　　　　    True：表示使用更精確的L2範數進行計算（即兩個方向的倒數的平方和再開方）
　　　　　　False：表示使用L1範數（直接將兩個方嚮導數的絕對值相加）
```
          
    
    

In [ ]:
import cv2
import numpy as np

img = cv2.imread("desk.png")

blurred = cv2.GaussianBlur(img, (3, 3), 0)
gray = cv2.cvtColor(blurred, cv2.COLOR_RGB2GRAY)


edge_output = cv2.Canny(gray, 70, 140,apertureSize=3)
cv2.imshow("Canny Edge", edge_output)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>輪廓檢測- contour detection
-----
   輪廓通常是從邊緣獲得的，但它們的目標是成為對象輪廓。
   因此，它們需要是閉合曲線。您可以將它們視為邊界。當它們從邊緣獲得時，您需要連接邊緣以獲得閉合輪廓。

## <font color=red>為了更加準確，OpenCV做contour偵測前，要把原圖透過閾值化處理轉成binary image(二元圖像)，或是經過Canny邊界檢測
-----
![image.png](attachment:image.png)

## <font color=red>contour偵測處理流程
-----
![image-2.png](attachment:image-2.png)

## <font color=red>把輪廓找出來-findContours語法
--------
### contours, hierarchy = cv2.findContours(source_image, retrieval_mode, approx_method)
--------
### output的部分有兩塊
    1. contours-找出來的輪廓
    2. hierarchy-找出來的輪廓，彼此間有沒有關係? 有沒有小輪廓是在大輪廓裡面的?
--------
### input的部分
    1.source_image-目標照片
    2.retrieval_mode-擷取模式  
          cv2.RETR_EXTERNAL-只擷取最外圍的輪廓  
          cv2.RETR_LIST-擷取大大小小所有輪廓，擷取結果沒有父子關係，大家都平等  
          cv2.RETR_CCOMP-會列出內、外兩層關係  
          cv2.RETR_TREE-會列出完整所有關係
    3.approx_method-輪廓紀錄方式
          cv2.CHAIN_APPROX_NONE-最精細紀錄模式
          cv2.CHAIN_APPROX_SIMPLE-只記錄畫出輪廓的關鍵點
          
    
    

## <font color=red>把輪廓畫出來-drawContours語法
--------
```
  marked_img = cv2.drawContours(img,
                                contours,
                                contourIdx,
                                color,   
                                thickness,
                                lineType = cv.LINE_8,
                                hierarchy = cv.Mat(),
                                maxLevel = INT_MAX,
                                offset = cv.Point(0, 0)))
```

--------
### input的部分
1.img-BGR目標照片，要標註輪廓的照片  
2.contours-我們偵測到的輪廓  
3.contourIdx-你要畫的輪廓，如果你要畫全部的輪廓，就用-1  
4.color-BGR，畫輪廓的顏色  
[5.lineType](https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html#gaf076ef45de481ac96e0ab3dc2c29a777)  
6.offset-偏離程度
          
    
    

## <font color=red>contour偵測案例

In [ ]:
import cv2
import matplotlib.pyplot as plt

#依照圖片格式，把圖片讀入
image = cv2.imread('sample shapes.png')
cv2.imshow("origin",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#轉成灰階
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("gray",gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#cv2.THRESH_OTSU演算法會找到最優閾值，讓我們獲得一個最佳的binary image
#ret 是 return value，就是門檻值
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
cv2.imshow('binary image', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>進行contour偵測前，有一個關鍵
### 圖最好是黑底白圖(目標是白色的)

In [ ]:
#原本的狀態
binary_im

In [ ]:
#相反的狀態
~binary_im

In [ ]:
#透過~，就可以
inverted_binary_im= ~binary_im
cv2.imshow('inverse of binary image', inverted_binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
contours,hierarchy = cv2.findContours(inverted_binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#-1是全部輪廓都要畫
#(0,255,0)是框線的顏色
#3是線的厚度
with_contours = cv2.drawContours(image, contours, -1,(0,255,0),3)
cv2.imshow('Detected contours on RGB image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>資料夾裡面有一個people的圖片，麻煩幫我把人框出來

## <font color=red ><答案>

In [ ]:
import cv2
import matplotlib.pyplot as plt

#依照圖片格式，把圖片讀入
image = cv2.imread('people.png')
cv2.imshow("origin",image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#轉灰階
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [ ]:
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#-1是全部輪廓都要畫
#(0,255,0)是框線的顏色
#3是線的厚度
with_contours = cv2.drawContours(image, contours, -1,(0,255,0),3)
cv2.imshow('Detected contours on image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>可不可以幫我不同的框用不同的顏色
![image-4.png](attachment:image-4.png)

## <font color=red ><答案>

In [ ]:
import cv2

#依照圖片格式，把圖片讀入
image = cv2.imread('people.png')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

with_contours = cv2.drawContours(image, contours, 0,(0,255,0),5)
with_contours = cv2.drawContours(image, contours,2,(0,0, 255),15)
with_contours = cv2.drawContours(image, contours,3,(255,0, 0),25)
cv2.imshow('Detected contours on image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 看一下其實框出來很多組資料，不是只有三個人
len(contours)

4

In [ ]:
#那沒看到的那是甚麼東西?
import cv2

#依照圖片格式，把圖片讀入
image = cv2.imread('people.png')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

with_contours = cv2.drawContours(image, contours, 1,(0,255,0),5)
cv2.imshow('Detected contours on image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>有時候我們是希望用一個長方形把物體框起來的
![image.png](attachment:image.png)

## <font color=red >cv2.boundingRect
----
### 矩形邊框（Bounding Rectangle）是說，用一個最小的矩形，把找到的形狀包起來。
    
```

    cv2.boundingRect(img)
    
```
----
```
     img是一個二值圖，也就是它的參數；
     返回四個值，分別是x，y，w，h（ x，y是矩型左上點的坐標，w，h是矩型的寬和高）
```
-------


## <font color=red>cv2.rectangle怎麼用?
![image-2.png](attachment:image-2.png)

In [ ]:
import cv2
import matplotlib.pyplot as plt

#依照圖片格式，把圖片讀入
image = cv2.imread('people.png')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
#找出輪廓
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#畫出紅色的輪廓
with_contours = cv2.drawContours(image, contours, -1,(0,0,255),2)
#根據0號輪廓把起點座標和長寬算出來
x, y, w, h= cv2.boundingRect(contours[0])
#畫一下這個長方框
cv2.rectangle(with_contours,(x,y), (x+w,y+h), (255,0,0), 8)

cv2.imshow('Detected contours on image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>Hierarchy-輪廓階級
<!--180020177X-204-->

![image.png](attachment:image.png)

In [ ]:
import cv2
#看一下原始圖案
image = cv2.imread('contour_hierarchy.png')
imagecopy= image.copy()
cv2.imshow('Original image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#前面都是黑白圖了，那你覺得下面這步要不要做?
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret, im_binary = cv2.threshold(gray_image, 0, 255, cv2.THRESH_BINARY)
#only find EXTERNAL
contours,hierarchy = cv2.findContours(im_binary,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
with_contours = cv2.drawContours(image, contours, -1,(0,0,255),5)
cv2.imshow('Detected contours on image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#我們看一下層級的資訊
hierarchy

array([[[ 1, -1, -1, -1],
        [-1,  0, -1, -1]]], dtype=int32)

## <font color=red>Hierarchy-輪廓資料怎麼解讀
-----
    1.有幾個contour，就有幾個元素。
    2.[ a, b, c, d]分別代表"後一個輪廓"、"前一個輪廓"、"父輪廓"(是誰的父輪廓)、"內嵌輪廓"(是誰的小孩)的索引編號，-1就是沒有

In [ ]:
contours,hierarchy = cv2.findContours(im_binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
with_contours = cv2.drawContours(image, contours, 0,(255,0,0),5)
with_contours = cv2.drawContours(image, contours, 1,(0,255,0),5)
with_contours = cv2.drawContours(image, contours, 2,(0,0,255),5)
with_contours = cv2.drawContours(image, contours, 3,(255,0,255),2)
cv2.imshow('Detected contours on image', with_contours)
print(hierarchy)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[ 1 -1 -1 -1]
  [-1  0  2 -1]
  [-1 -1  3  1]
  [-1 -1 -1  2]]]


## <font color=red>Hierarchy-用螺帽案例講解一下
-----
    1.有幾個contour，就有幾個元素。
    2.[ a, b, c, d]分別代表"後一個輪廓"、"前一個輪廓"、"父輪廓"(是誰的父輪廓)、"內嵌輪廓"(是誰的小孩)的索引編號，-1就是沒有

In [ ]:
import cv2
image_3chan = cv2.imread('nut_bolt.png')
cv2.imshow('Original image', image_3chan)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
gray_image = cv2.cvtColor(image_3chan, cv2.COLOR_BGR2GRAY)
ret,binary_im = cv2.threshold(gray_image,250,255,cv2.THRESH_BINARY)
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
hierarchy

array([[[ 1, -1, -1, -1],
        [-1,  0,  2, -1],
        [-1, -1, -1,  1]]], dtype=int32)

In [ ]:
for i in range(0, len(contours)):
    contour_info= hierarchy[0][i, :]
    print('Hierarchy information of current contour:')
    print(contour_info)
    # 非父非子的就是螺栓
    if contour_info[2]==-1 and contour_info[3]==-1:
        with_contours = cv2.drawContours(image_3chan,contours,i,[0,255,0],thickness=3)
        print('螺栓輪廓找到了!')
    # 非父但是是人家兒子的就是螺帽孔
    if contour_info[2]==-1 and contour_info[3]!=-1:
        with_contours = cv2.drawContours(with_contours,contours,i,[0,0,255],thickness=3)
        print('螺栓孔找到了!')

Hierarchy information of current contour:
[ 1 -1 -1 -1]
螺栓輪廓找到了!
Hierarchy information of current contour:
[-1  0  2 -1]
Hierarchy information of current contour:
[-1 -1 -1  1]
螺栓孔找到了!


In [ ]:
cv2.imshow('Contours marked on RGB image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>資料夾裡面有張照片，請幫我把籃網框起來，可以嗎?
![image.png](attachment:image.png)

## <font color=red ><答案>

In [ ]:
import cv2

image = cv2.imread('basketball.jpg')

#我們等一下需要一張乾淨的底圖來標示
imageCopy= image.copy()
cv2.imshow('BGR image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#轉灰階
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#轉二元圖
ret,binary_im = cv2.threshold(gray_image,100, 255,cv2.THRESH_BINARY)
cv2.imshow('binary', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#設定一下drawContours的參數
contours_to_plot= -1
plotting_color= (0,255,0)
thickness= -1

with_contours = cv2.drawContours(image,contours, contours_to_plot, plotting_color,thickness)
cv2.imshow('contours', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
for cnt in contours:
    x,y,w,h = cv2.boundingRect(cnt)
    image = cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,255),2)
cv2.imshow('contours', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#根據面積，挑出籃網的部分
required_contour = max(contours, key = cv2.contourArea)
x,y,w,h = cv2.boundingRect(required_contour)
img_copy2 = cv2.rectangle(imageCopy, (x,y),(x+w, y+h),(0,255,255),2)
cv2.imshow('largest contour', img_copy2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red > cv2.contourArea
----
### 計算輪廓的面積
    
```

    cv2.contourArea(contour， oriented=True)
    
```
----
```
     contour：表示某輸入單個輪廓，為array
    
     oriented：表示某個方向上輪廓的面積值，這裡指順時針或者逆時針。若為True，該函數返回一個帶符號的面積值，正負值取決於
               輪廓的方向（順時針還是逆時針），若為False，表示以絕對值返回
```
-------


## <font color=red > cv2.arcLength
----
### 計算輪廓的周長
    
```

    cv2.arcLength(contour， closed=True)
    
```
----
```
     contour：表示某輸入單個輪廓，為array
    
     closed：用於指示曲線是否封閉
```
-------


## <font color=red > cv2.approxPolyDP
----
### cv2.approxPolyDP()函數是輪廓近似函數，是opencv中對指定的點集進行多邊形逼近的函數，其逼近的精度可通過參數設置
    
```

    approxPolyDP(curve, epsilon, closed, approxCurve=None)
    
```
----
```
     curve：表示輸入的點集
     
     epslion：指定的精度，也即原始曲線與近似曲線之間的最大距離，不過這個值我們一般按照周長的大小進行比較
     
     close：若為True，則說明近似曲線為閉合的；反之，若為False，則斷開
```
-------


In [ ]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('contour2.png')
img1 = img.copy()
img2 = img.copy()

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

_, thresh = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY)

contours, hierarchy= cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

cnt = contours[0]
img1 = cv2.drawContours(img1, [cnt], -1, (0, 255, 0), 3)     #你可能想問這裡我們為什麼要加[]，你前面給人家脫衣服，現在不用穿回去嗎?

#改用近似畫法
#抓近似差距，可以嘗試看看設更小的數
epsilon = 0.1*cv2.arcLength(cnt, True)
approx = cv2.approxPolyDP(cnt, epsilon, True)
img2 = cv2.drawContours(img2, [approx], -1, (0, 255, 0), 3)


plt.rcParams['figure.figsize'] = [200, 100]
plt.rcParams['font.size'] = 150

img = cv2.cvtColor(img , cv2.COLOR_BGR2RGB)
plt.subplot(1,3,1)
plt.imshow(img)
plt.xticks([]), plt.yticks([])
plt.title('origin image BGR')

img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2RGB)
plt.subplot(1,3,2)
plt.imshow(img1)
plt.xticks([]), plt.yticks([])
plt.title('closed image ')

img2 = cv2.cvtColor(img2  , cv2.COLOR_BGR2RGB)
plt.subplot(1,3,3)
plt.imshow(img2)
plt.xticks([]), plt.yticks([])
plt.title('open  image')
plt.show()

## <font color=red > cv2.minEnclosingCircle
----
### 實現輪廓的外接圓
    
```

    minEnclosingCircle(contour)
    
```
----
```
     contour：表示輸入的輪廓

```
-------


## <font color=red>Contour Matching-輪廓比對
<!--180020177X-224-->

## <font color=red>Hu moments-利用擷取特徵點，來達到比對目的
<!--180020177X-245-->
---
### [參考連結](https://chtseng.wordpress.com/2017/03/24/%E4%BD%BF%E7%94%A8moments%E6%8F%8F%E8%BF%B0%E8%91%89%E7%89%87%E9%A1%9E%E5%9E%8B/)

In [ ]:
import cv2
image = cv2.imread('many fruits.png')
cv2.imshow('Original image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray', gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
ret,binary_im = cv2.threshold(gray_image,245,255,cv2.THRESH_BINARY)
cv2.imshow('binary', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
binary_im= ~binary_im
cv2.imshow('inverted binary', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
contours,hierarchy = cv2.findContours(binary_im,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

In [ ]:
with_contours = cv2.drawContours(image,contours,-1,(0,0,255),3)
cv2.imshow('contours marked on RGB image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red>把香蕉挑出來

In [ ]:
ref_image = cv2.imread('bananaref.png')
cv2.imshow('Reference image', ref_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
gray_image = cv2.cvtColor(ref_image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Grayscale image', gray_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: ignored

In [ ]:
ret,binary_im = cv2.threshold(gray_image,245,255,cv2.THRESH_BINARY)
cv2.imshow('Binary image', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
binary_im= ~binary_im
cv2.imshow('inverted binary image', binary_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: ignored

In [ ]:
ref_contour_list,hierarchy = cv2.findContours(binary_im,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
with_contours = cv2.drawContours(ref_image,ref_contour_list,-1,(0,0,255),3)
cv2.imshow('contours marked on RGB image',with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: ignored

In [ ]:
len(ref_contour_list)

1

In [ ]:
#取出關鍵contour作為模板
reference_contour = ref_contour_list[0]

## <font color=red>cv2.matchShapes-把兩個contour拿來比較一下
--------
```
               cv2.matchShapes( contour1,
                                contour2,
                                method,
                                parameter)
```

--------
### input的部分
    1.contour1-比對對象
    2.contour2-比對基準
    3.method-
![image-2.png](attachment:image-2.png)
    4.parameter：方法特定參數，現在不支持了，設置成默認值0即可。
          
    
    

In [ ]:
dist_list= [ ]
for cnt in contours:
    retval=cv2.matchShapes(cnt, reference_contour,1,0)
    dist_list.append(retval)

In [ ]:
dist_list

#這是每一個圖，按順序跟模板比較的結果

[1.9329380069362876,
 1.6618014776874734,
 1.771151523726344,
 1.8150005423795166,
 1.2692130505335848,
 1.269213050534173]

In [ ]:
sorted_list= dist_list.copy()
sorted_list.sort()
sorted_list

#我們複製原本data，重新排序後，我們現在知道按照相似順序的排列是怎樣

[1.2692130505335848,
 1.269213050534173,
 1.6618014776874734,
 1.771151523726344,
 1.8150005423795166,
 1.9329380069362876]

In [ ]:
ind1_dist= dist_list.index(sorted_list[0])
ind2_dist= dist_list.index(sorted_list[1])
#值越小，代表距離越近，代表圖形越像
#取出前兩名的圖案

In [ ]:
banana_cnts= [ ]
banana_cnts.append(contours[ind1_dist])
banana_cnts.append(contours[ind2_dist])

#把前兩名的輪廓整理出來

In [ ]:
with_contours = cv2.drawContours(image, banana_cnts,-1,(255,0,0),3)
cv2.imshow('contours marked on RGB image', with_contours)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>現在我們是把所有香蕉挑出來，可不可以挑出如下圖的那一個直立香蕉就好?
--------
![image.png](attachment:image.png)

## <font color=red ><答案>
<!--  比較長寬尺寸判斷出來 -->

In [ ]:
imagecopy= cv2.imread('many fruits.png')

for cnt in banana_cnts:
    x,y,w,h = cv2.boundingRect(cnt)
    if h>w:
        cv2.rectangle(imagecopy,(x,y),(x+w,y+h),(255,0,0),2)
cv2.imshow('Upright banana marked on RGB image', imagecopy)
cv2.waitKey(0)
cv2.destroyAllWindows()

## <font color=red ><小測驗>資料夾裡面有一張照片，可不可以幫我把B挑出來
<!-- 可以換換看模板照片比較一下b1b2 -->
-----
![image.png](attachment:image.png)

## <font color=red ><答案>

In [ ]:
import cv2
#讀取照片
image = cv2.imread('phrase_handwritten.png')

In [ ]:
#轉灰階
gray_image = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
#轉二元
ret,binary_im = cv2.threshold(gray_image,0,255,cv2.THRESH_OTSU)
cv2.imshow( 'binary image' , binary_im )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#找輪廓
contours_list,hierarchy = cv2.findContours(binary_im,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
for cnt in contours_list:
    x,y,w,h = cv2.boundingRect(cnt)
    cv2.rectangle(image,(x,y),(x+w,y+h),(0, 255, 255),2)
cv2.imshow( 'Contours marked on RGB image' , image )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#做模板
ref_gray = cv2.imread('b3.png', cv2.IMREAD_GRAYSCALE)
ret, ref_binary = cv2.threshold(ref_gray,0,255,cv2.THRESH_OTSU)
cv2.imshow( 'Reference image' , ref_binary )
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
#開始比較
ref_contour_list,hierarchy = cv2.findContours(ref_binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
if len(ref_contour_list)==1:
    ref_contour= ref_contour_list[0]
else:
    print('找到的模板輪廓超過1個，需要確認一下用哪一個?')

ctr= 0
dist_list= []
for cnt in contours_list:
    retval=cv2.matchShapes(cnt, ref_contour,cv2.CONTOURS_MATCH_I1,0)
    dist_list.append(retval)
    ctr= ctr+1

min_dist= min(dist_list)   #找出距離最近的
ind_min_dist= dist_list.index(min_dist)   #挑出那張圖

In [ ]:
required_cnt= contours_list[ind_min_dist]
x,y,w,h = cv2.boundingRect(required_cnt)
imagecopy= cv2.imread('phrase_handwritten.png')

cv2.rectangle(imagecopy,(x,y),(x+w,y+h),(255, 0, 0),2)
cv2.imshow( 'Detected B' , imagecopy )
cv2.waitKey(0)
cv2.destroyAllWindows()